### ISSUE TITLE
migration from 2.0.0 beta.10 to 2.2.2

### ISSUE THREAD

**Issue by MEBY98** [vueComponent/ant-design-vue#4425]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
"vue": "^3.0.0-0", win 10 2015 pro

### Reproduction link
[https://github.com/MEBY98/LextoolF-frontend](https://github.com/MEBY98/LextoolF-frontend)

### Steps to reproduce
i was working with 2.0.0 beta and i needed the component a-image (component that not exist in that version)... i tried to install 2,2,2 to get that component the program start to do these errors

### What is expected?
i didnt expect any errors cuz is the same major version... or maybe is just problem on my pc

### What is actually happening?
Uncaught (in promise) TypeError: expose is not a function
at setup (Form.js?d65b:323)
at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
at setupStatefulComponent (runtime-core.esm-bundler.js?5c40:6191)
at setupComponent (runtime-core.esm-bundler.js?5c40:6152)
at mountComponent (runtime-core.esm-bundler.js?5c40:4400)
at processComponent (runtime-core.esm-bundler.js?5c40:4376)
at patch (runtime-core.esm-bundler.js?5c40:3991)
at mountChildren (runtime-core.esm-bundler.js?5c40:4180)
at processFragment (runtime-core.esm-bundler.js?5c40:4339)
at patch (runtime-core.esm-bundler.js?5c40:3984)

---
i hope this post be ussefull.. grettings

**Comment by zkwolf** [comment]
you should update your vue and @vue/compiler-sfc version to 3.1.x

**Comment by MEBY98** [comment]
> you should update your vue and @vue/compiler-sfc version to 3.1.x

ty man all problems solved... rlly usefull
