### ISSUE TITLE
After upgrading from vue2.6 to 3.0.0 and ant-design-vue from 1.6.7 to 2.2.2, the createForm of the Form component does not exist. Do you have any suggestions for handling the 1.x to 2.

### ISSUE THREAD

**Issue by NescafeYi** [vueComponent/ant-design-vue#4436]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Google Chrome , 版本 91.0.4472.124

### Reproduction link
[https://1x.antdv.com/components/form-cn/#components-form-demo-basic](https://1x.antdv.com/components/form-cn/#components-form-demo-basic)

### Steps to reproduce
1.x版本:
data() {
this.form = this.$form.createForm(this)
return { }
},

已注册Form:  app.config.globalProperties.$form = Form

error:  TypeError: this.$form.createForm is not a function

### What is expected?
兼容1.x，form的createForm 写法

### What is actually happening?
发生报错，找不到原来的createForm 方法了

**Comment by zkwolf** [comment]
确实没了，这里break change了

**Comment by tangjinzhou** [comment]
https://2x.antdv.com/docs/vue/migration-v2-cn
